-- AlterTable
ALTER TABLE `Category` MODIFY `game` ENUM('VALORANT', 'FREEFIRE', 'CSGO', 'FORTNITE', 'PLANOS') NOT NULL;

-- AlterTable
ALTER TABLE `Product` MODIFY `game` ENUM('VALORANT', 'FREEFIRE', 'CSGO', 'FORTNITE', 'PLANOS') NOT NULL;
